Feature/improve image
websight-io/kyanite pull request #13
Opened 2022-08-31 12:59 UTC by nowak-pawel-ds

2022-08-31 13:33 UTC, marcell-pal-ds requested changes

2022-08-31 13:33 UTC, marcell-pal-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/card/_ws_dialog/.content.xml
> +                <adress
Typo in 'adress'

2022-08-31 13:33 UTC, marcell-pal-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/card/common/image/.content.xml
> +            <is-4by3
You could also use the `sling:hideChildren` attribute this way:
`sling:hideChildren="[is-4by3,is-3by5,...]"`

This is maybe a more readable format, but of course feel free to use the already implemented way as the result should be the same anyways.

2022-09-01 06:52 UTC, nowak-pawel-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/card/common/image/.content.xml
> +            <is-4by3
I tried it on include tag and it did not work :/ where should I insert it?

2022-09-01 07:11 UTC, marcell-pal-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/card/common/image/.content.xml
> +            <is-4by3
This code snippet works for me:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/110379062/187853025-b5bb68c7-e8a3-4a97-b336-6b5da2ca8011.png">

I also realized, that putting whitespace between multiple elements does not work, so if you have more elements, you need to use simply the commas like I did in the example of my first comment here.

2022-09-01 07:29 UTC, nowak-pawel-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/card/common/image/.content.xml
> +            <is-4by3
it did not work for me :/ tried it

2022-09-01 07:30 UTC, marcell-pal-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/card/common/image/.content.xml
> +            <is-4by3
Alright.

2022-09-01 07:30 UTC, marcell-pal-ds approved these changes

2022-09-02 06:43 UTC, arturwujczak approved these changes

2022-09-02 06:57 UTC, paweljozwicki approved these changes

2022-09-02 08:09 UTC, merged