Feature/create tag component
websight-io/kyanite pull request #14
Opened 2022-08-31 13:24 UTC by arturwujczak

2022-08-31 13:38 UTC, marcell-pal-ds requested changes

2022-08-31 13:38 UTC, marcell-pal-ds commented on core/src/main/java/pl/ds/bulma/components/models/TagsListComponent.java
> +    private String hasAddons;
`boolean` type could be used here just like in the `TagComponent` class.

2022-08-31 13:38 UTC, marcell-pal-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/tag/_ws_dialog/.content.xml
> +                    checkedByDefault="false"
As I know `checkedByDefault` is already false by default

2022-08-31 13:38 UTC, marcell-pal-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/tagslist/_ws_dialog/.content.xml
> +                    checkedByDefault="false"
Same here.

2022-08-31 13:54 UTC, nowak-pawel-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/pagecontainer/.content.xml
> +          allowedComponents="[Bulma.io,Howlite]"/>
We decided to use components from howlite?

2022-08-31 13:54 UTC, nowak-pawel-ds commented on ui.apps/src/main/jcr_root/apps/bulma/components/tag/_ws_dialog/.content.xml
> +        <modifiers
It is only four fields, it could be on one tab I think. Better from user experience perspective

2022-09-01 06:05 UTC, arturwujczak commented on ui.apps/src/main/jcr_root/apps/bulma/components/pagecontainer/.content.xml
> +          allowedComponents="[Bulma.io,Howlite]"/>
It's a mistake, I needed it for something else.

2022-09-01 06:14 UTC, arturwujczak commented on ui.apps/src/main/jcr_root/apps/bulma/components/tag/_ws_dialog/.content.xml
> +        <modifiers
I made it so that it was similar to the button, but ok, maybe one tab is enough for 4 fields.

2022-09-01 07:04 UTC, marcell-pal-ds approved these changes

2022-09-01 07:31 UTC, nowak-pawel-ds commented on core/src/main/java/pl/ds/bulma/components/models/TagComponent.java
> +    @Default(booleanValues = false)
Primitive boolean is by default false so you do not need to add Default values

2022-09-01 07:31 UTC, nowak-pawel-ds commented on core/src/main/java/pl/ds/bulma/components/models/TagsListComponent.java
> +    @Default(booleanValues = false)
Same here

2022-09-01 07:38 UTC, nowak-pawel-ds approved these changes

2022-09-01 07:42 UTC, merged