WOS-168 Content Text weight
websight-io/kyanite pull request #173
Opened 2023-04-26 11:26 UTC by andrechern

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-04-26 11:27 UTC, andrechern commented
I have read the Dynamic Solutions Individual Contributor License Agreement (CLA) Document and I hereby sign the CLA

2023-04-26 11:32 UTC, andrechern commented
recheck

2023-04-26 13:07 UTC, AdrianStaskiewicz requested changes
Please change PR destination to 'develop' branch

2023-04-28 06:34 UTC, paweljozwicki approved these changes

2023-04-28 08:27 UTC, merged