WOS-167 Title and Content components: added new component properties …
websight-io/kyanite pull request #174
Opened 2023-04-26 11:35 UTC by AdrianStaskiewicz

…- color and shadow

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-05-02 12:25 UTC, Rafal-DS requested changes

2023-05-02 12:25 UTC, Rafal-DS commented on application/backend/src/main/java/pl/ds/bulma/components/helpers/ColorService.java
> +    if (resource != null) {
How about an early exit to reduce nesting?
if (resource == null) {
return new ArrayList<>();
}

2023-05-02 12:25 UTC, Rafal-DS commented on application/backend/src/main/java/pl/ds/bulma/components/models/ContentComponent.java
>  public class ContentComponent {
Adding bold to text removes the color:
<img width="271" alt="Screenshot 2023-04-28 at 16 00 29" src="https://user-images.githubusercontent.com/121929316/235168527-4636f5b7-a189-4053-8eff-3010d21e812d.png">

2023-05-02 12:25 UTC, Rafal-DS commented on application/backend/src/main/java/pl/ds/bulma/components/models/TitleComponent.java
> +  private String shadeBw;
What does "Bw" mean?

2023-05-02 12:25 UTC, Rafal-DS commented on application/backend/src/main/resources/apps/bulma/components/content/dialog/.content.json
> +      "shadeContainer": {
I don't see this any shade container in config dialog:
<img width="726" alt="Screenshot 2023-04-28 at 16 23 52" src="https://user-images.githubusercontent.com/121929316/235174403-d94b640f-95f3-4714-b99d-cc9239c74957.png">

2023-05-04 06:10 UTC, paweljozwicki commented on application/backend/src/main/java/pl/ds/bulma/components/models/ContentComponent.java
>  public class ContentComponent {
Removing colors by adding bold, underlining, etc. is a known issue. Let's go ahead and resolve it in a separate issue.

2023-05-05 11:03 UTC, AdrianStaskiewicz commented on application/backend/src/main/java/pl/ds/bulma/components/models/TitleComponent.java
> +  private String shadeBw;
black and white ;)

2023-05-09 14:09 UTC, Rafal-DS commented on application/backend/src/main/resources/libs/bulma/components/content/dialog/.content.json
> +          "sling:resourceSuperType": "/libs/bulma/components/common/text/color",
Someone told me that, we should write paths like this:
"bulma/components/common/text/color"
not like this
"/libs/bulma/components/common/text/color"
so that the resource can be overwritten.

2023-05-16 08:43 UTC, paweljozwicki commented on application/backend/src/main/java/pl/ds/bulma/components/models/TitleComponent.java
> +            = new ColorService(resource, "/libs/bulma/components/common/text/color",
You can change the path to a relative one. It will give the possibility to overwrite it in the project easily.

2023-05-16 08:47 UTC, paweljozwicki commented on application/backend/src/main/java/pl/ds/bulma/components/helpers/ColorService.java
> +    this.colorBw = getElementsFromListByPrefix(colorsList, "bw_");
I'm wondering if we could read the prefix (shade_) and map colors by it. Then we could find shades by this prefix. It should be more elastic. I mean, in the project we could overwrite the whole colors and shades with something totally different.

2023-05-17 11:51 UTC, paweljozwicki commented on application/backend/src/main/java/pl/ds/bulma/components/helpers/ColorService.java
> +    this.colorBw = getElementsFromListByPrefix(colorsList, "bw_");
Accepted for now. We can refactor it later.

2023-05-17 11:51 UTC, paweljozwicki approved these changes

2023-05-17 11:53 UTC, Rafal-DS approved these changes

2023-05-17 12:24 UTC, merged