WOS-179 Icon: added icon size property
websight-io/kyanite pull request #184
Opened 2023-05-04 12:14 UTC by AdrianStaskiewicz

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-05-12 07:52 UTC, szymontodads requested changes
I've built project locally, and FE seems to handle the size, but ME does not show the dropdown.

![Screenshot 2023-05-12 at 09 50 46](https://github.com/websight-io/bulma/assets/121932253/fee79714-0b86-499a-94ca-a4aaaa148696)
![Screenshot 2023-05-12 at 09 50 43](https://github.com/websight-io/bulma/assets/121932253/8f8ad698-7981-4212-a3f7-e0187fedef38)

2023-05-15 09:13 UTC, paweljozwicki commented on application/backend/src/main/java/pl/ds/bulma/components/models/IconComponent.java
> +import java.util.ArrayList;
I think there are some unused imports?

2023-05-15 09:13 UTC, paweljozwicki commented on application/backend/src/main/java/pl/ds/bulma/components/models/IconComponent.java
> +    String mappingPath = "/libs/bulma/components/common/icon/containersize/defaultsizemappings";
You can use a path starting from `bulma/` so it should be possible to be overwritten in a project.

2023-05-15 11:58 UTC, paweljozwicki approved these changes

2023-05-15 12:27 UTC, merged