WSIO-132 Service for contact form
websight-io/kyanite pull request #212
Opened 2023-05-26 10:47 UTC by andrechern

Contact us component was changed.

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-05-26 11:09 UTC, Rafal-DS reviewed
@andrechern later there will be quarkus service, that actually sends the email, right?

2023-05-26 12:01 UTC, andrechern commented
Yes

> @andrechern later there will be quarkus service, that actually sends the email, right?

yes

2023-05-26 12:09 UTC, paweljozwicki commented on application/backend/src/main/resources/libs/bulma/components/contactform/contactform.html
> +        data-config-http-end-point='${model.configEndpoint}'>
We have this configuration added to the body: https://github.com/websight-io/bulma/blob/main/application/backend/src/main/resources/libs/bulma/components/page/body.html#L23

We can remove it from the body, but we need to update js files as well to use both configs from the form definition

2023-06-21 07:46 UTC, paweljozwicki commented on application/backend/src/main/resources/libs/bulma/components/contactform/contactform.html
> +            <input class="input" type="text" name="subject" placeholder="Full Name" required>
It has incorrect name

2023-06-21 07:47 UTC, paweljozwicki requested changes

2023-06-21 07:47 UTC, paweljozwicki commented on application/backend/src/main/resources/libs/bulma/components/contactform/contactform.html
> +            <input class="input" type="text" name="subject" placeholder="Full Name" required>
It has incorrect name

2023-06-22 13:21 UTC, merged