WSIO-315 configurable background for page
websight-io/kyanite pull request #263
Opened 2023-07-20 12:47 UTC by Rafal-DS

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-07-24 11:21 UTC, Mikilll94 requested changes
1.
![Screenshot 2023-07-24 at 13 20 59](https://github.com/websight-io/kyanite/assets/17653648/00f5dd7a-08b9-4444-b989-cf867b38ad53)


Fancy background checkbox should be removed. It is no longer needed.

2. 
![Screenshot 2023-07-24 at 13 19 44](https://github.com/websight-io/kyanite/assets/17653648/c299ad25-7910-42bd-8583-cec7d67777cc)

When changing page properties using this icon, the change is not applied immediately. I need to refresh the page.

2023-07-24 12:45 UTC, Rafal-DS commented
> ![Screenshot 2023-07-24 at 13 20 59](https://user-images.githubusercontent.com/17653648/255574733-00f5dd7a-08b9-4444-b989-cf867b38ad53.png)
> 
> Fancy background checkbox should be removed. It is no longer needed.
> 
> 
> ![Screenshot 2023-07-24 at 13 19 44](https://user-images.githubusercontent.com/17653648/255574500-c299ad25-7910-42bd-8583-cec7d67777cc.png)
> 
> When changing page properties using this icon, the change is not applied immediately. I need to refresh the page.

1. Removed
2. IMO it is an issue with the core CMS. Need to report it there.

2023-07-24 12:52 UTC, paweljozwicki approved these changes

2023-07-25 07:59 UTC, Mikilll94 requested changes
![Screenshot 2023-07-25 at 09 58 42](https://github.com/websight-io/kyanite/assets/17653648/11461dfa-e1de-47d2-8db3-fd22d76c7bfb)

1. I would just call it "Background" and put it below "Title". We know it refers to page.
2. "Background" should be marked as required similar to "Navbar fixed position".

2023-07-25 13:02 UTC, Mikilll94 approved these changes

2023-07-25 13:03 UTC, merged