WSIO-314 added background config for hero
websight-io/kyanite pull request #264
Opened 2023-07-20 12:48 UTC by Rafal-DS

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-07-24 11:58 UTC, Mikilll94 requested changes
Build is failing, probably e2e tests

2023-07-24 11:58 UTC, Mikilll94 commented on applications/common/frontend/src/atomic-design-system/03-organism/o.hero/o.hero.scss
> +    @include o-hero-background.o-background;
let's rename this to `o-background-circles`

2023-07-24 12:53 UTC, paweljozwicki approved these changes

2023-07-25 12:23 UTC, Rafal-DS commented
> 

e2e fixed

2023-07-25 13:16 UTC, Mikilll94 approved these changes

2023-07-25 13:19 UTC, merged