Added short doc about css variables.
websight-io/kyanite pull request #319
Opened 2023-10-03 10:04 UTC by kchra

## Description

## Motivation and Context

## Screenshots (if appropriate)

## Upgrade notes (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) labeled with `bug`
- [ ] New feature (non-breaking change which adds functionality) labeled with `enhancement`
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the [code standards](../CONTRIBUTING.md) of this project.
- [ ] My change requires updating the documentation. I have updated the documentation accordingly.

2023-10-05 11:21 UTC, Mikilll94 requested changes
I would write this in a different way. Here is my proposition.

Kyanite library defines a set of CSS variables. They can be used and overwritten in project using Kyanite. We can divide them into the following categories:

- colors

```css
background-color: var(--color-primary--200);
```

- font-size `--font-size-{value}`

```css
font-size: var(--font-size-12);
```

...

This is just my proposition. You can ignore it if you don't like it.

2023-10-05 11:21 UTC, Mikilll94 commented on applications/common/frontend/README.md
> +CSS Variables are generated automaticly in 'global-variables.scss'. These variables can be `used` or `redefined` in your project.
typo in `automaticly`

2023-10-05 11:21 UTC, Mikilll94 commented on applications/common/frontend/README.md
> +IMPORTANT: The names of maps defined in the '/atomic-design-system/00-token/' and '/bulma-overwrite/_variables.scss' can't be changed because the rest of 'atomic-design-system' uses css variables fro
typo in `global-varibles`

2023-10-09 06:41 UTC, paweljozwicki commented
What do you think about adding information about how to overwrite those variables?

2023-10-12 13:29 UTC, kchra commented on applications/common/frontend/README.md
> +CSS Variables are generated automaticly in 'global-variables.scss'. These variables can be `used` or `redefined` in your project.
fixed

2023-10-12 13:29 UTC, kchra commented on applications/common/frontend/README.md
> +IMPORTANT: The names of maps defined in the '/atomic-design-system/00-token/' and '/bulma-overwrite/_variables.scss' can't be changed because the rest of 'atomic-design-system' uses css variables fro
fixed

2023-10-12 13:53 UTC, Mikilll94 approved these changes

2023-10-17 14:07 UTC, merged