WOS-22 Add content component
websight-io/kyanite pull request #37
Opened 2022-09-14 08:24 UTC by piotr-szewczul-ds

2022-09-14 08:35 UTC, nowak-pawel-ds requested changes
Please add size class for the dialog and in the content classes

2022-09-14 10:16 UTC, nowak-pawel-ds approved these changes

2022-09-15 10:27 UTC, paweljozwicki approved these changes

2022-09-15 10:29 UTC, paweljozwicki reviewed
Just think that you should reformat code according to codestyle changes made by @nowak-pawel-ds

2022-09-16 08:25 UTC, merged